version: '2.2'

services:
  config-server:
    build:
        context: Car_Rental-Server_Config
        dockerfile: Dockerfile
    image: noroom113/car-rental-config-server:${CAR_RENTAL_SERVER_CONFIG_COMMIT_HASH}
    ports:
      - "8888:8888"
    networks:
      - spring-cloud-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8888/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    environment:
      SPRING_PROFILES_ACTIVE: native

  eureka-server:
    build:
      context: Car_Rental-Eureka_Server
      dockerfile: Dockerfile
    image: noroom113/car-rental-eureka-server:${CAR_RENTAL_EUREKA_SERVER_COMMIT_HASH}
    ports:
      - "8761:8761"
    depends_on:
      config-server:
        condition: service_healthy
    networks:
      - spring-cloud-network
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:8761/actuator/health"]
        interval: 30s
        timeout: 10s
        retries: 3
    environment:
      EUREKA_PORT: 8761
      SPRING_PROFILES_ACTIVE: docker_dev
      SPRING_CLOUD_CONFIG_URI: http://config-server:8888
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka
      EUREKA_INSTANCE_HOSTNAME: eureka-server

  accessibility-service:
    build:
      context: accessibility-service
      dockerfile: Dockerfile
    image: noroom113/car-rental-accessibility-service:${ACCESSIBILITY_SERVICE_COMMIT_HASH}
    ports:
      - "6871:6871"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:6871/actuator/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - spring-cloud-network
    depends_on:
      - eureka-server
    environment:
      ACCESSIBILITY_SERVICE_PORT: 6871
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka
      SPRING_CLOUD_CONFIG_URI: http://config-server:8888
      SPRING_PROFILES_ACTIVE: docker_dev

  auth-service:
    build:
      context:
        Car_Rental-Auth_Service
      dockerfile: Dockerfile
    image: noroom113/car-rental-auth-service:${CAR_RENTAL_AUTH_SERVICE_COMMIT_HASH}
    ports:
      - "6872:6872"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:6872/actuator/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - spring-cloud-network
    depends_on:
      - eureka-server
    environment:
      AUTH_SERVICE_PORT: 6872
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka
      SPRING_CLOUD_CONFIG_URI: http://config-server:8888
      SPRING_PROFILES_ACTIVE: docker_dev


  user-service:
    build:
      context: Car_Rental-User_Service
      dockerfile: Dockerfile
    image: noroom113/car-rental-user-service:${CAR_RENTAL_USER_SERVICE_COMMIT_HASH}
    ports:
      - "6868:6868"
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:6868/actuator/health"]
        interval: 30s
        timeout: 10s
        retries: 3
    networks:
      - spring-cloud-network
    depends_on:
      - accessibility-service
      - eureka-server
    environment:
        USER_SERVICE_PORT: 6868
        EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka
        SPRING_CLOUD_CONFIG_URI: http://config-server:8888
        SPRING_PROFILES_ACTIVE: docker_dev

  car-service:
    build:
      context: Car_Rental-Car_Service
      dockerfile: Dockerfile
    image: noroom113/car-rental-car-service:${CAR_RENTAL_CAR_SERVICE_COMMIT_HASH}
    ports:
      - "6869:6869"
    depends_on:
      - accessibility-service
      - eureka-server
    networks:
      - spring-cloud-network
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:6869/actuator/health"]
        interval: 30s
        timeout: 10s
        retries: 3
    environment:
        CAR_SERVICE_PORT: 6869
        EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka
        SPRING_CLOUD_CONFIG_URI: http://config-server:8888
        SPRING_PROFILES_ACTIVE: docker_dev

  contract-service:
    build:
      context: Car_Rental-Contract_Service
      dockerfile: Dockerfile
    image: noroom113/car-rental-contract-service:${CAR_RENTAL_CONTRACT_SERVICE_COMMIT_HASH}
    ports:
      - "6870:6870"
    depends_on:
      - accessibility-service
      - eureka-server
    networks:
      - spring-cloud-network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:6870/actuator/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
    environment:
      CONTRACT_SERVICE_PORT: 6870
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka
      SPRING_CLOUD_CONFIG_URI: http://config-server:8888
      SPRING_PROFILES_ACTIVE: docker_dev

  gateway-service:
    build:
      context: Car_Rental-Gateway_Service
      dockerfile: Dockerfile
    image: noroom113/car-rental-gateway-service:${CAR_RENTAL_GATEWAY_SERVICE_COMMIT_HASH}
    ports:
      - "8762:8762"
    depends_on:
      - config-server
      - eureka-server
      - user-service
      - car-service
      - contract-service
      - accessibility-service
      - auth-service
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8762/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - spring-cloud-network
    environment:
      GATEWAY_SERVICE_PORT: 8762
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka
      SPRING_CLOUD_CONFIG_URI: http://config-server:8888
      SPRING_PROFILES_ACTIVE: docker_dev

networks:
  spring-cloud-network:
    name: spring-cloud-network
    driver: bridge
