version: '1.0'
services:
  config-server:
    build:
        context: RentCarServerConfig
        dockerfile: Dockerfile
    ports:
      - "8888:8888"
    expose:
      - 8888

  eurekaserver:
    build:
      context: Car_Rent_Management_Server
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
    expose:
      - 8761
    depends_on:
      - config-server

  zuulserver:
    build:
      context: Car_Rent_Management_Gateway
      dockerfile: Dockerfile
    ports:
      - "8762:8762"
    expose:
      - 8762
    depends_on:
      - eurekaserver

  customermanagementservice:
    build:
      context: CustomerManagementService
      dockerfile: Dockerfile
    ports:
      - "6868:6868"
    expose:
      - 6868
    depends_on:
      - eurekaserver
      - zuulserver

  carmanagementservice:
    build:
      context: Car_Management_Service
      dockerfile: Dockerfile
    ports:
      - "6869:6869"
    expose:
      - 6869
    depends_on:
      - eurekaserver
      - zuulserver
networks:
  default: