version: '2.2'

services:
  config-server:
    image: noroom113/car-rental-config-server
    ports:
      - "8888:8888"
    networks:
      - prod-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8888/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    environment:
      SPRING_PROFILES_ACTIVE: native

  eureka-server:
    image: noroom113/car-rental-eureka-server
    ports:
      - "8761:8761"
    depends_on:
      config-server:
        condition: service_healthy
    networks:
      - prod-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    environment:
      EUREKA_PORT: 8761
      SPRING_PROFILES_ACTIVE: docker_prod
      SPRING_CLOUD_CONFIG_URI: http://config-server:8888
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka
      EUREKA_INSTANCE_HOSTNAME: eureka-server

  accessibility-service:
    image: noroom113/car-rental-accessibility-service
    ports:
      - "6871:6871"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:6871/actuator/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - prod-network
    depends_on:
      - eureka-server
    environment:
      ACCESSIBILITY_SERVICE_PORT: 6871
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka
      SPRING_CLOUD_CONFIG_URI: http://config-server:8888
      SPRING_PROFILES_ACTIVE: docker_prod

  auth-service:
    image: noroom113/car-rental-auth-service
    ports:
      - "6872:6872"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:6872/actuator/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - prod-network
    depends_on:
      - eureka-server
    environment:
      AUTH_SERVICE_PORT: 6872
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka
      SPRING_CLOUD_CONFIG_URI: http://config-server:8888
      SPRING_PROFILES_ACTIVE: docker_prod


  user-service:
    image: noroom113/car-rental-user-service
    ports:
      - "6868:6868"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6868/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - prod-network
    depends_on:
      - accessibility-service
      - eureka-server
    environment:
      USER_SERVICE_PORT: 6868
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka
      SPRING_CLOUD_CONFIG_URI: http://config-server:8888
      SPRING_PROFILES_ACTIVE: docker_prod

  car-service:
    image: noroom113/car-rental-car-service
    ports:
      - "6869:6869"
    depends_on:
      - accessibility-service
      - eureka-server
    networks:
      - prod-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6869/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    environment:
      CAR_SERVICE_PORT: 6869
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka
      SPRING_CLOUD_CONFIG_URI: http://config-server:8888
      SPRING_PROFILES_ACTIVE: docker_prod

  contract-service:
    image: noroom113/car-rental-contract-service
    ports:
      - "6870:6870"
    depends_on:
      - accessibility-service
      - eureka-server
    networks:
      - prod-network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:6870/actuator/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
    environment:
      CONTRACT_SERVICE_PORT: 6870
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka
      SPRING_CLOUD_CONFIG_URI: http://config-server:8888
      SPRING_PROFILES_ACTIVE: docker_prod

  gateway-service:
    image: noroom113/car-rental-gateway-service
    ports:
      - "8762:5120"
    depends_on:
      - config-server
      - eureka-server
      - user-service
      - car-service
      - contract-service
      - accessibility-service
      - auth-service
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8762/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - prod-network
    environment:
      GATEWAY_SERVICE_PORT: 8762
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka
      SPRING_CLOUD_CONFIG_URI: http://config-server:8888
      SPRING_PROFILES_ACTIVE: docker_prod

networks:
  prod-network:
    name: prod-network
    driver: bridge
