services:
  frontend:
    build:
      context: font-midproj-hdv
      target: development
    image: noroom113/font-midproj-hdv:${FONT_MIDPROJ_HDV_COMMIT_HASH}
    ports:
      - 3000:3000
    stdin_open: true
    restart: always
    develop:
      watch:
        - action: sync
          path: ./font-midproj-hdv
          target: /usr/src/app
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json
    networks:
      - react-express
    depends_on:
      - backend
      - nginx

  backend:
    restart: always
    build:
      context: back-midproj-hdv
      target: dev-envs
    image: noroom113/back-midproj-hdv:${BACK_MIDPROJ_HDV_COMMIT_HASH}
    develop:
      watch:
        - action: sync
          path: ./back-midproj-hdv
          target: /usr/src/app
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json
    depends_on:
      - mongo
    networks:
      - express-mongo
      - react-express
    expose:
      - 3000
  mongo:
    restart: always
    image: mongo:4.2.0
    volumes:
      - ./mongo_dump:/dump
      - ./mongo_data:/data/db
    networks:
      - express-mongo
    expose:
      - 27017
  nginx:
    restart: always
    image: nginx:latest
    volumes:
      - ./nginx_prod.conf:/etc/nginx/nginx.conf
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
    networks:
      - react-express
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  certbot:
    image: certbot/certbot:v1.8.0
    container_name: certbot
    volumes:
      - /data/certbot/letsencrypt:/etc/letsencrypt
      - /data/certbot/www:/var/www/certbot
      - /data/servers-data/certbot/log:/var/log
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    environment:
      - CERT_DIR_PATH=/data/certbot/letsencrypt
      - WEBROOT_PATH=/data/certbot/www
      - LE_RENEW_HOOK=docker restart nginx
      - DOMAINS=www.noroom113.me
      - EMAIL=tienthuan05082002@gmail.com
      - EXP_LIMIT=30
      - CHECK_FREQ=30
      - CHICKENEGG=1
      - STAGING=0
networks:
  react-express:
  express-mongo:

volumes:
  mongo_data: