services:
  frontend:
    build:
      context: font-midproj-hdv
      target: development
    image: noroom113/font-midproj-hdv:${FONT_MIDPROJ_HDV_COMMIT_HASH}
    ports:
      - 3000:3000
    stdin_open: true
    restart: always
    develop:
      watch:
        - action: sync
          path: ./font-midproj-hdv
          target: /usr/src/app
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json
    networks:
      - react-express
    depends_on:
      - backend
      - nginx

  backend:
    restart: always
    build:
      context: back-midproj-hdv
      target: dev-envs
    image: noroom113/back-midproj-hdv:${BACK_MIDPROJ_HDV_COMMIT_HASH}
    develop:
      watch:
        - action: sync
          path: ./back-midproj-hdv
          target: /usr/src/app
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json
    depends_on:
      - mongo
    networks:
      - express-mongo
      - react-express
    expose:
      - 3000
  mongo:
    restart: always
    image: mongo:4.2.0
    volumes:
      - ./mongo_dump:/dump
      - ./mongo_data:/data/db
    networks:
      - express-mongo
    expose:
      - 27017
  nginx:
    restart: always
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./data/nginx:/etc/nginx/conf.d
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
    networks:
      - react-express
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
networks:
  react-express:
  express-mongo:

volumes:
  mongo_data: