services:
  frontend:
    build:
      context: font-midproj-hdv
      target: development
    image: noroom113/font-midproj-hdv:${FONT_MIDPROJ_HDV_COMMIT_HASH}
    ports:
      - 3000:3000
    stdin_open: true
    restart: always
    develop:
      watch:
        - action: sync
          path: ./font-midproj-hdv
          target: /usr/src/app
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json
    networks:
      - react-express
    depends_on:
      - backend
      - nginx

  backend:
    restart: always
    build:
      context: back-midproj-hdv
      target: dev-envs
    image: noroom113/back-midproj-hdv:${BACK_MIDPROJ_HDV_COMMIT_HASH}
    develop:
      watch:
        - action: sync
          path: ./back-midproj-hdv
          target: /usr/src/app
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json
    depends_on:
      - mongo
    networks:
      - express-mongo
      - react-express
    expose:
      - 3000
  mongo:
    restart: always
    image: mongo:4.2.0
    volumes:
      - ./mongo_dump:/dump
      - ./mongo_data:/data/db
    networks:
      - express-mongo
    expose:
      - 27017
  nginx:
    restart: always
    image: jonasal/nginx-certbot:latest
    environment:
      CERTBOT_EMAIL: 'tienthuan05082002@gmail.com'
    env_file:
      - ./nginx-certbot.env
    ports:
      - '80:80'
      - '443:443'
    networks:
      - react-express
    volumes:
      - nginx_secrets:/etc/letsencrypt
      - ./user_conf.d:/etc/nginx/user_conf.d
networks:
  react-express:
  express-mongo:

volumes:
  mongo_data:
  nginx_secrets: { }
  certificates: { }