@startuml
autonumber
' Define participants
participant Staff
participant UI
participant Server

' Define objects
alt login success
    UI -> UI: redirect to home page
    Staff -> UI: Choose analysis Usr by Revenue
    UI -> Server: Get data Usr by Revenue
    Server -> UI: Response data Usr by Revenue
    UI -> UI: Show analysis Usr by Revenue
end
@enduml
