@startuml
autonumber
participant User
participant UI
participant Server

User -> UI: Login Success
UI -> Server: Get List of Cars
Server -> UI: Response (List of Cars)
UI -> UI: Show Home Page
User -> UI: Choose a car to see details
UI -> Server: Get Car Details
Server -> UI: Response (Car Details)
UI -> UI: Show Car Details
User -> UI: Click on Book Now
UI -> UI: Show Booking Form
loop until form fields are valid
    User -> UI: Fill the form (Name, address, email, phone number, start and end time)
    UI -> UI: Validate form fields (Name, address, email, phone number)
    alt Invalid
        UI -> UI: Show error message
    end
    UI -> Server: Validate time (start and end time)
    Server -> UI: Response (Valid or Invalid)
    alt Invalid
        UI -> UI: Show error message
    end
    alt All Fields Valid
        UI -> UI: Enable Payment Button
    end
end
User -> UI: Click payment
UI -> Server: Process Payment
Server -> UI: Response (Success or Failure)
alt Payment Success
    UI -> UI: Show Success Message
else
    UI -> UI: Show Failure Message
end
@enduml
