@startuml
autonumber
' Define participants
participant User
participant UI
participant Server

' Define objects
User -> UI: Open app
UI -> UI: Show login page
' Define conditions
loop until (Login Success?)
    alt Has Account
        User -> UI: Fill `identity cards id`
        User -> UI: Fill `Password`
        User -> UI: Click Login
        UI -> Server: Send request to server
        Server -> Server: Validate data
        Server -> Server: Check data
        Server -> UI: Send response to client
        alt Login Success
            UI -> UI: Show success message
        else Login Fail
        UI -> UI: Show error message
        end
    else No Account
        User -> UI: Click Register
        UI -> UI: Show Register page
        User -> UI: Enter `identity cards id`
        User -> UI: Enter `email`
        User -> UI: Enter `Name`
        User -> UI: Enter `Password`
        User -> UI: Enter `Confirm Password`
        User -> UI: Click Register
        UI -> Server: Send request to server
        Server -> Server: Validate data
        Server -> Server: Save data
        Server -> UI: Send response to client
        alt Register Success
            UI -> UI: Show success message
        else Register Fail
        UI -> UI: Show error message
        end
    end
end
UI -> UI: Redirect to Home page
@enduml
