@startuml
'https://plantuml.com/activity-diagram-beta
'Delivery car to user
|Staff|
start
:Follow the contract to get the car;
repeat
  :Check the car;
  if (Car is OK?) then (no)
    :Call the mechanic;
    :Fix the car;
  else (yes)
  endif
repeat while (Car is OK?) is (no)
-> yes;
:confirm to User for delivery;
:Drive to the user follow\n address on the contract;
|User|
:Receive the car;
stop
@enduml
