@startuml
'https://plantuml.com/activity-diagram-beta

|User|
start
    :Click Login;
|UI|
    :Render login page;
|User|
    if (Has Account) then (yes)
        partition Login {
            repeat
                :Enter `Can cuoc cong dan`;
                :Enter `Password`;
                :Click Login;
|Server|
                :Send request to server;
                :Validate data;
                if (Data is valid) then (yes)
                    :Check data;
                else (no)
                endif
                :Send response to client;
|User|
                if (Login Success) then (yes)
                    else (no)
                    :Show error message;
                    endif
                repeat while (Login Success?) is (false)
        }
    else (no)
        partition Register {
            repeat
                :Click Register;
                repeat
                    if (Provide Data) is (take a picture) then
                        :Take a picture;
                    else (Using available photos)
                        :Choose photo from gallery;
                    endif
                     :Validate photo;
                repeat while (Photo is valid) is (false)
                -> true;
                :Enter `Password`;
                :Enter `Confirm Password`;
                :Click Register;
|Server|
                :Send request to server;
                :Validate data;
                if (Data is valid) then (yes)
                    :Save data;
                else (no)
                endif
                :Send response to client;
|User|
                if (Register Success) then (yes)
                    else (no)
                    :Show error message;
                    endif
            repeat while (Register Success?) is (false)
            -> true;
        }
    endif
:Redirect to Home page;
|UI|
stop
@enduml
