@startuml

class "User" as users {
  *id : long <<generated>>
  + name : string
  + email : string <<unique>>
  + password : string
  + created_at : datetime
  + updated_at : datetime
  --
  + indentity_card_id <<FK>>
  + driver_license_id <<FK>>
  + accessibility_id <<FK>>
}

class "IndentityCardId" as indentity_card_id {
  * id : long <<generated>>
  + number : string <<unique>>
  + imageBase64 : string
  + created_at : datetime
  + updated_at : datetime
}

class "DriverLicense" as driver_licenses {
  * id : long <<generated>>
  + number : string <<unique>>
  + imageBase64 : string
  + created_at : datetime
  + updated_at : datetime
}

class "Accessibility" as accessibilities {
  * id : long <<generated>>
  + name : string <<unique>>
  + created_at : datetime
  + updated_at : datetime
}

class "Car" as cars {
    * id : long <<generated>>
    + license_plate : string <<unique>>
    + brand : string
    + model : string
    + is_available : boolean
    + color : string
    + created_at : datetime
    + updated_at : datetime
    --
    + car_package_id <<FK>>
    + car_parameters_id <<FK>>
}

class "CarPackage" as car_packages {
    * id : long <<generated>>
    + packageName : string
    + pricePerHour : int
    + created_at : datetime
    + updated_at : datetime
}

class "CarParameters" as car_parameters {
    * id : long <<generated>>
    + number_of_doors : int
    + number_of_seats : int
    + fuel_type_id : int
    + gear_box_id : int
    + is_air_conditioning_available : boolean
}

class "RentalContract" as rental_contracts {
    * id : long <<generated>>
    + start_date : datetime
    + end_date : datetime
    + created_at : datetime
    + updated_at : datetime
    --
    + user_id <<FK>>
    + car_id <<FK>>
    + staff_id <<FK>>
}

users o-- indentity_card_id
users o-- driver_licenses
users o-- accessibilities
users <-- rental_contracts

cars o-- car_packages
cars o-- car_parameters
cars <-- rental_contracts

@enduml
