@startuml

class "User" as users {
  *id : long <<generated>>
  + name : string
  + email : string <<unique>>
  + password : string
  + created_at : datetime
  + updated_at : datetime
  --
  + indentity_card_id <<FK>>
  + driver_license_id <<FK>>
  + accessibility_id <<FK>>
}

class "IndentityCardId" as indentity_card_id {
  * id : long <<generated>>
  + number : string <<unique>>
  + imageBase64 : string
  + created_at : datetime
  + updated_at : datetime
}

class "DriverLicense" as driver_licenses {
  * id : long <<generated>>
  + number : string <<unique>>
  + imageBase64 : string
  + created_at : datetime
  + updated_at : datetime
}

class "Accessibility" as accessibilities {
  * id : long <<generated>>
  + name : string <<unique>>
  + created_at : datetime
  + updated_at : datetime
}

users o-- indentity_card_id
users o-- driver_licenses
users o-- accessibilities

@enduml
