@startuml
'https://plantuml.com/class-diagram

entity "User" as users {
  *id : long <<generated>>
  + name : string
  + email : string <<unique>>
  + password : string
  + created_at : datetime
  + updated_at : datetime
  --
  + identity_cards_id <<FK>>
  + driver_license_id <<FK>>
}

entity "IdentityCard" as identity_cards {
  * id : long <<generated>>
  + number : string <<unique>>
  + imageBase64 : string
  + created_at : datetime
  + updated_at : datetime
}

entity "DriverLicense" as driver_licenses {
  * id : long <<generated>>
  + number : string <<unique>>
  + imageBase64 : string
  + created_at : datetime
  + updated_at : datetime
}

entity "Accessibility" as accessibilities {
  * id : long <<generated>>
  + name : string <<unique>>
  + created_at : datetime
  + updated_at : datetime
}

entity "Car" as cars {
    * id : long <<generated>>
    + model : string
    + license_plate : string <<unique>>
    + brand : string
    + model : string
    + is_available : boolean
    + color : string
    + created_at : datetime
    + updated_at : datetime
    --
    + car_package_id <<FK>>
    + car_parameters_id <<FK>>
}

entity "CarPackage" as car_packages {
    + id : long <<generated>>
    + packageName : string
    + pricePerHour : int
    + created_at : datetime
    + updated_at : datetime
}

entity "CarParameters" as car_parameters {
    +  id : long <<generated>>
    +  number_of_doors : int
    +  number_of_seats : int
    +  fuel_type_id : int
    +  gear_box_id : int
    +  is_air_conditioning_available : boolean
}

entity "RentalContract" as rental_contracts {
    * id : long <<generated>>
    + start_date : datetime
    + end_date : datetime
    + created_at : datetime
    + updated_at : datetime
    --
    + user_id <<FK>>
    + car_id <<FK>>
    + staff_id <<FK>>
}

users ||--o{ rental_contracts
users ||--o{ accessibilities
users ||--|| identity_cards
users ||--|| driver_licenses

cars ||--o{ rental_contracts
cars }|--|| car_parameters
cars ||--|| car_packages

@enduml