@startuml
'https://plantuml.com/class-diagram

entity "User" as users {
  *id : long <<generated>>
  + name : string
  + email : string <<unique>>
  + password : string
  + created_at : datetime
  + updated_at : datetime
  --
  + identity_cards_id <<FK>>
  + driver_license_id <<FK>>
}

entity "IdentityCard" as identity_cards {
  * id : long <<generated>>
  + number : string <<unique>>
  + imageBase64 : string
  + created_at : datetime
  + updated_at : datetime
}

entity "DriverLicense" as driver_licenses {
  * id : long <<generated>>
  + number : string <<unique>>
  + imageBase64 : string
  + created_at : datetime
  + updated_at : datetime
}

entity "Accessibility" as accessibilities {
  * id : long <<generated>>
  + name : string <<unique>>
  + created_at : datetime
  + updated_at : datetime
}

users ||--o{ accessibilities
users ||--|| identity_cards
users ||--|| driver_licenses

@enduml