¡@startuml
'https://plantuml.com/class-diagram
class entity.RentalContract {
- Long id
- Date startDate
- Date endDate
- Long carId
- Long customerId
- Long? staffId
}

class repository.RentalContractRepository {
}

class service.RentalContractService {
- RentalContractRepository rentalContractRepository
+ RentalContract createRentalContract(RentalContract rentalContract)
+ List<RentalContract> getAllRentalContracts()
+ RentalContract getRentalContractById(Long id)
+ RentalContract updateRentalContract(RentalContract rentalContract)
+ void deleteRentalContractById(Long id)
}

class controller.RentalContractController {
- RentalContractService rentalContractService
+ ResponseEntity<RentalContract> createRentalContract(RentalContract rentalContract)
+ ResponseEntity<List<RentalContract>> getAllRentalContracts()
+ ResponseEntity<RentalContract> getRentalContractById(Long id)
+ ResponseEntity<RentalContract> updateRentalContract(RentalContract rentalContract)
+ ResponseEntity<Void> deleteRentalContractById(Long id)
}

org.springframework.data.jpa.repository.JpaRepository <|-- repository.RentalContractRepository

repository.RentalContractRepository --> entity.RentalContract

service.RentalContractService --> repository.RentalContractRepository
controller.RentalContractController --> service.RentalContractService


@enduml