@startuml
interface repository.CarParametersRepository {
}
class service.CarService {
- CarRepository carRepository
- CarPackageRepository carPackageRepository
- CarParametersRepository carParametersRepository
+ List<Car> getAllCars(Integer,Sort.Direction)
+ List<CarPackage> getCarPackages()
+ List<Car> getAvailableCars(Integer,Sort.Direction)
+ Car getCar(Long)
+ Car saveCar(Car)
+ Car editCar(Long,Car)
+ Car setCarParameters(Long,CarParameters)
+ Car setCarPackage(Long,String)
+ void deleteCar(Long)
+ CarPackage saveCarPackage(CarPackage)
+ void deleteCarPackage(Long)
}


class entities.CarParameters {
- Long id
- FuelType fuelType
- GearBoxType gearBoxType
- Integer numberOfDoors
- Integer numberOfSeats
- Boolean isAirConditioningAvailable
- Car car
}

interface repository.CarPackageRepository {
~ Optional<CarPackage> findByPackageName(String)
}

enum constant.FuelType {
+  PETROL
+  DIESEL
+  LPG
+  ELECTRIC
}

class entities.CarPackage {
- Long id
- String packageName
- Integer pricePerHour
}

interface repository.CarRepository {
~ List<Car> findCars(Pageable)
~ List<Car> findAvailableCars(Pageable)
}

class controller.CarController {
- CarService carService
+ List<Car> getAllCars(Integer,Sort.Direction)
+ List<CarPackage> getCarPackages()
+ List<Car> getAvailableCars(Integer,Sort.Direction)
+ Car getCar(Long)
+ Car saveCar(Car)
+ Car editCar(Long,Car)
+ Car setCarParameters(Long,CarParameters)
+ Car setCarPackage(Long,String)
+ void deleteCar(Long)
+ CarPackage saveCarPackage(CarPackage)
+ void deleteCarPackage(Long)
}


class entities.Car {
- Long id
- String registrationNr
- String brand
- String model
- Boolean isAvailable
- CarPackage carPackage
- CarParameters carParameters
}

enum constant.GearBoxType {
+  MANUAL
+  AUTOMATIC
}

org.springframework.data.jpa.repository.JpaRepository <|-- repository.CarParametersRepository
org.springframework.data.jpa.repository.JpaRepository <|-- repository.CarPackageRepository
org.springframework.data.jpa.repository.JpaRepository <|-- repository.CarRepository

repository.CarParametersRepository --> entities.CarParameters
repository.CarPackageRepository --> entities.CarPackage
repository.CarRepository --> entities.Car

service.CarService --> repository.CarRepository
service.CarService --> repository.CarPackageRepository
service.CarService --> repository.CarParametersRepository

controller.CarController --> service.CarService

CarParameters o-- constant.FuelType
CarParameters o-- constant.GearBoxType
@enduml