name: Build and Deploy Dev

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          token: ${{ secrets.PAT_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker
        uses: docker/setup-buildx-action@v3
      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install docker-compose-plugin
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Print current directory
        run: |
          echo "Current directory: $GITHUB_WORKSPACE"
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '17'
      # Gradle action from GitHub marketplace is used for better maintainability
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Push Docker Hub
        run: |
          pwd
      - name: Update submodules
        run: |
          chmod +x gradlew
          gradle buildAllProjectsAndPushDockerImage --info --stacktrace
      - name: Build and push Docker image
        run: |
          docker-compose -f compose-dev.yaml up -d --pull
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to server
        # Use "appleboy/ssh-action" to deploy the image to the server via SSH
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Pull the image that was pushed to DockerHub above
            docker-compose -f compose-dev.yaml pull
            
            # Stop and remove the current (if any)
            docker-compose -f compose-dev.yml down
            
            # Run a new container with the image pulled above
            docker-compose -f compose-dev.yaml up -d

   
   
