name: Build and Deploy Dev

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
    build:
      needs: [update_env_dev]
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
          with:
            submodules: recursive
            token: ${{ secrets.PAT_TOKEN }}
        - name: Login to Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
        - name: Print current directory
          run: |
            echo "Current directory: $GITHUB_WORKSPACE"
        - uses: actions/setup-java@v4
          with:
            distribution: 'temurin' # See 'Supported distributions' for available options
            java-version: '17'
        # Gradle action from GitHub marketplace is used for better maintainability
        - name: Setup Gradle
          uses: gradle/actions/setup-gradle@v3
        - name: Push Docker Hub
          run: |
            pwd
        - name: Update submodules
          run: |
            chmod +x gradlew
            gradle buildAllProjects
              docker-compose -f compose-dev.yaml build
        - name: push Docker image
          run: |
            docker compose -f compose-dev.yaml --env-file ./config/.env.dev build --push
    deploy:
      needs: [build]
      runs-on: self-hosted
      steps:
        - uses: actions/checkout@v3
          with:
            submodules: recursive
            token: ${{ secrets.PAT_TOKEN }}
        - name: push Docker image
          run: |
            docker compose -f compose-dev.yaml --env-file ./config/.env.dev up -d >/dev/null 2>&1

   
   
