name: Build and Deploy Dev

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Print current directory
        run: |
          echo "Current directory: $GITHUB_WORKSPACE"
      - name: Install OpenJDK 11
        run: |
          sudo apt update
          sudo apt install -y openjdk-11-jdk
      - name: Set JAVA_HOME
        run: |
          echo "export JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64" >> $GITHUB_ENV
      - name: Print Java version
        run: java -version

      - name: Push Docker Hub
        run: |
          chmod 777 gradlew
          bash ./gradlew buildAllProjectsAndPushDockerImage

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to server
        # Use "appleboy/ssh-action" to deploy the image to the server via SSH
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Pull the image that was pushed to DockerHub above
            docker-compose -f compose-dev.yaml pull
            
            # Stop and remove the current (if any)
            docker-compose -f compose-dev.yml down
            
            # Run a new container with the image pulled above
            docker-compose -f compose-dev.yaml up -d

   
   
