name: Build and Deploy Dev

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  update_env_dev:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get submodule commit hashes
        run: |
          SUBMODULE_HASHES=$(git submodule status | awk '{print $1, $2}')
          echo "$SUBMODULE_HASHES" > submodule_hashes.txt

      - name: Create .env.dev file
        run: |
          echo "Creating new environment file: .env.dev.new"
          echo "# Submodule commit hashes for development" > ./config/.env.dev.new
          
          while read -r line; do
          submodule=$(echo $line | awk -F"-" '{print $1}' | sed 's/_/-/g' | awk '{for (i=1;i<=NF;i++) $i=toupper(substr($i,1,1)) tolower(substr($i,2)); print $0}')
          hash=$(echo $line | awk -F"-" '{print $2}')
          echo "Processing submodule: $submodule"
          echo "Adding submodule commit hash: $hash"
          echo "${submodule}_COMMIT_HASH=$hash" >> ./config/.env.dev.new
          done < submodule_hashes.txt
          echo "Environment file generation completed: .env.dev.new"
          

  - name: Check diff
        id: check_diff
        run: |
          if ! git diff --quiet --exit-code ./config/.env.dev ./config/.env.dev.new; then
            echo "Changes detected in .env.dev"
            mv ./config/.env.dev.new ./config/.env.dev  # Ghi đè tệp .env.dev cũ bằng tệp .env.dev.new
            echo "::set-output name=env_diff::true"
          else
            echo "No changes detected in .env.dev"
            echo "::set-output name=env_diff::false"
          fi

      - name: Commit and push .env.dev if there are changes
        if: steps.check_diff.outputs.env_diff == 'true'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add ./config/.env.dev
          git commit -m "Update submodule hashes for development"
          git push
  build:
    needs: [update_env_dev]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          token: ${{ secrets.PAT_TOKEN }}
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Print current directory
        run: |
          echo "Current directory: $GITHUB_WORKSPACE"
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '17'
      # Gradle action from GitHub marketplace is used for better maintainability
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Push Docker Hub
        run: |
          pwd
      - name: Update submodules
        run: |
          chmod +x gradlew
          gradle buildAllProjects
            docker-compose -f compose-dev.yaml build
      - name: push Docker image
        run: |
          docker compose -f compose-dev.yaml --env-file ./config/.env.dev build --push
  deploy:
    needs: [build]
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          token: ${{ secrets.PAT_TOKEN }}
      - name: push Docker image
        run: |
          docker compose -f compose-dev.yaml --env-file ./config/.env.dev up -d >/dev/null 2>&1