name: Build and Deploy Prod

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: self-hosted-prod
    steps:
      - name: Chown user
        run: |
          sudo chown -R $USER:$USER $GITHUB_WORKSPACE
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ secrets.PAT_TOKEN }}
          clean: false
      - name: Print current directory
        run: |
          pwd
      - name: Run Docker compose
        run: |
          docker rm -vf $(docker ps -aq)
          docker rmi -f $(docker images -aq
          docker compose --env-file ./config/.env.prod -f compose-prod.yaml up -d --watch --force-recreate
